name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      env:
        USER_ID: ${{ secrets.USER_ID }}
        API_KEY: ${{ secrets.API_KEY }}
      run: USER_ID=$USER_ID API_KEY=$API_KEY go test -v ./...
